### ISSUE TITLE
Got ACTION_MOVE event but don't have an active pointer id.

### ISSUE THREAD

**Issue by sytolk** [googlesamples/android-SwipeRefreshListFragment#2]
http://stackoverflow.com/questions/35848182/swiperefreshlayout-got-action-move-event-but-dont-have-an-active-pointer-id

**Comment by synergywebdesigners** [comment]
http://stackoverflow.com/questions/35568075/swiperefreshlayout-got-error-and-cannot-refresh-load-more-in-the-first-time You Try this Link I hope this link is work on Your End

**Comment by autocircled** [comment]
@synergywebdesigners not working that link :(

**Comment by codingjeremy** [comment]
This sample has been deprecated/archived (check README for more information on newer samples related to this technology). 

[As recommended by GitHub][1], we are closing all issues and pull requests.

[1]: https://help.github.com/en/articles/archiving-repositories
